### ISSUE TITLE
Function Login ใช้ไม่ได้ครับ

### ISSUE THREAD

**Issue by keereetoo** [ekkamon/Class-PHP-Auto-TopupFireFree#1]
Function Login ใช้ไม่ได้ครับ

**Comment by 4khalil** [comment]
Notice: Undefined index: open_id in C:\xampp\htdocs\a\freefire.class.php on line 50
Array ( [error] => error_params ) 
it not work they cann't get open_id frome the respons !

**Comment by keereetoo** [comment]
ตัว API ปัจจุบันไม่สามารถใช้ได้แล้วครับ มีตัวทีสามารถใช้ได้มัยครับ 
ถ้ามีรบกวนช่วยอัพเดทให้หน่อยนะครับ หรือ ต้องการขาย ลองเสนอราคามานะครับ

ขอบคุณครับ
![image](https://user-images.githubusercontent.com/37771645/111159837-16f66080-85cc-11eb-9ad3-e484360d2068.png)

**Comment by 4khalil** [comment]
> The current API is no longer available. Is there a one that can be used?
> If there is disturbance, please update it a little or want to sell, try to bid
> 
> Thank you
> ![picture](https://user-images.githubusercontent.com/37771645/111159837-16f66080-85cc-11eb-9ad3-e484360d2068.png)

it' not me who made this api, i'm asking about a solution
